#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: scripts/xbox-boot-evidence-report.sh [output.md] [synthetic-out-dir] [real-b3-out-dir]

Generates a Markdown status report from xbox-boot-evidence-summary.sh. The
report is intended for handoff: it separates proven synthetic evidence from
real-asset B3/B4/B5 gaps and records the next command to run.

Defaults:
  output.md:         xbox-browser-boot-status.md
  synthetic-out-dir: build-browser-boot-verify-synthetic
  real-b3-out-dir:   build-real-b3-matrix
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
output="${1:-${repo_root}/xbox-browser-boot-status.md}"
synthetic_dir="${2:-${repo_root}/build-browser-boot-verify-synthetic}"
real_dir="${3:-${repo_root}/build-real-b3-matrix}"

case "${output}" in
    /*) ;;
    *) output="${repo_root}/${output}" ;;
esac
case "${synthetic_dir}" in
    /*) ;;
    *) synthetic_dir="${repo_root}/${synthetic_dir}" ;;
esac
case "${real_dir}" in
    /*) ;;
    *) real_dir="${repo_root}/${real_dir}" ;;
esac

tmp_summary="$(mktemp "${TMPDIR:-/tmp}/xemu-boot-evidence-summary.XXXXXX")"
trap 'rm -f "${tmp_summary}"' EXIT

"${repo_root}/scripts/xbox-boot-evidence-summary.sh" "${synthetic_dir}" "${real_dir}" >"${tmp_summary}"

value_for() {
    local line="$1"
    local key="$2"
    local token

    for token in ${line}; do
        case "${token}" in
            "${key}="*)
                printf '%s' "${token#*=}"
                return
                ;;
        esac
    done
}

status_for() {
    local item="$1"
    local line

    line="$(grep "^BOOT_EVIDENCE item=${item} " "${tmp_summary}" || true)"
    if [ -z "${line}" ]; then
        printf 'missing'
        return
    fi
    value_for "${line}" status
}

latest_line() {
    local file="$1"
    local pattern="$2"

    if [ ! -f "${file}" ]; then
        return
    fi
    grep -E "${pattern}" "${file}" | tail -n 1 || true
}

next_command_line() {
    "${repo_root}/scripts/xbox-boot-next-step.sh" "${synthetic_dir}" "${real_dir}" 2>/dev/null || true
}

summary_line="$(grep '^BOOT_EVIDENCE_SUMMARY ' "${tmp_summary}")"
summary_result="$(value_for "${summary_line}" result)"
synthetic_native="$(value_for "${summary_line}" synthetic_native)"
synthetic_wasm="$(value_for "${summary_line}" synthetic_wasm)"
real_b3="$(value_for "${summary_line}" real_b3)"
real_b4="$(value_for "${summary_line}" real_b4)"
real_b5="$(value_for "${summary_line}" real_b5)"
next_step="$(value_for "${summary_line}" next)"
real_readiness_log="$(value_for "$(grep '^BOOT_EVIDENCE item=real_fixture_ready ' "${tmp_summary}" || true)" log)"
real_log="$(value_for "$(grep '^BOOT_EVIDENCE item=b3_real_assets ' "${tmp_summary}" || true)" log)"
flash_line="$(latest_line "${real_readiness_log}" '^REAL_FIXTURE_READY item=flash ')"
hdd_line="$(latest_line "${real_readiness_log}" '^REAL_FIXTURE_READY item=hdd ')"
mcpx_line="$(latest_line "${real_readiness_log}" '^REAL_FIXTURE_READY item=mcpx ')"
eeprom_line="$(latest_line "${real_readiness_log}" '^REAL_FIXTURE_READY item=eeprom ')"
real_b3_failure_line="$(latest_line "${real_log}" '^REAL_B3_EVIDENCE result=fail|^BOOT_REAL_B3_MATRIX_RESULT result=fail')"
display_failure_line="$(latest_line "${real_log}" '^DISPLAY_CAPTURE_EVIDENCE result=fail')"
runtime_failure_line="$(latest_line "${real_log}" '^BROWSER_RUNTIME_EVIDENCE result=fail')"
next_line="$(next_command_line)"
next_command="$(printf '%s\n' "${next_line}" | sed -n 's/.* command_json="\([^"]*\)".*/"\1"/p')"
next_reason="$(value_for "${next_line}" reason)"

cat >"${output}" <<EOF
# Xbox Browser Boot Status

Generated by \`scripts/xbox-boot-evidence-report.sh\`.

## Summary

| Field | Value |
| --- | --- |
| Overall result | ${summary_result} |
| Synthetic native milestone | ${synthetic_native} |
| Synthetic wasm milestone | ${synthetic_wasm} |
| Real B3 storage boot | ${real_b3} |
| Real B4 visible display | ${real_b4} |
| Real B5 browser usability | ${real_b5} |
| Next step | ${next_step} |

## Evidence

| Item | Status | Meaning |
| --- | --- | --- |
| Synthetic aggregate gate | $(status_for synthetic_gate) | No-private-assets regression gate completed. |
| Docker build scaffold | $(status_for docker_build_scaffold) | Native and wasm Docker build scripts preserve required i386, TCI, browser-boot, and sysroot settings. |
| Synthetic B0 native/wasm | $(status_for b0_synthetic_native_wasm) | Both native and wasm constructed the Xbox machine. |
| Synthetic B1 native/wasm | $(status_for b1_synthetic_native_wasm) | Both native and wasm loaded synthetic firmware memory. |
| Synthetic B2 native/wasm | $(status_for b2_synthetic_native_wasm) | Both native and wasm initialized core Xbox devices. |
| Marker comparison | $(status_for synthetic_marker_compare) | Native and wasm marker sets match through the expected synthetic level. |
| Browser-block bridge | $(status_for b3_browser_block_bridge) | C-to-JS HDD open/read bridge is proven only with synthetic storage. |
| Browser host prerequisite | $(status_for b5_host_prereq) | COOP/COEP/CORP, artifacts, persistence, and host checks pass. |
| Browser runtime prerequisite | $(status_for b5_runtime_prereq) | Real browser synthetic run starts, logs, and times out deterministically. |
| Real fixture layout | $(status_for real_fixture_layout) | Ignored local fixture directory scaffolding is documented and tested without creating private assets. |
| Real fixture readiness | $(status_for real_fixture_ready) | Non-emulating check for private flash/HDD fixtures and fixed-size MCPX/EEPROM blobs. |
| Real fixture manifest | $(status_for real_fixture_manifest) | No-emulation handoff artifact with readiness and git privacy evidence. |
| Real fixture preflight | $(status_for real_fixture_preflight) | Real fixture discovery and size validation status. |
| Real B3 assets | $(status_for b3_real_assets) | Requires \`scripts/xbox-real-b3-evidence-check.sh\` to pass on the real matrix log. |
| Real B4 display | $(status_for b4_visible_display) | Requires B4 marker plus non-empty browser display capture evidence. |
| Real B5 browser | $(status_for b5_real_browser) | Requires \`scripts/xbox-browser-runtime-evidence-check.sh\` to pass on real selected-assets smoke. |

## Diagnostics

| Signal | Latest evidence |
| --- | --- |
| Fixture flash | ${flash_line:-not reported} |
| Fixture HDD | ${hdd_line:-not reported} |
| Fixture MCPX | ${mcpx_line:-not reported} |
| Fixture EEPROM | ${eeprom_line:-not reported} |
| Real B3 failure | ${real_b3_failure_line:-not reported} |
| Real B4 failure | ${display_failure_line:-not reported} |
| Real B5 failure | ${runtime_failure_line:-not reported} |
| Next command | reason=${next_reason:-unknown} command=${next_command:-unknown} |

## Next Commands

Ask the machine-readable helper for the next command:

\`\`\`sh
scripts/xbox-boot-next-step.sh
\`\`\`

Run the no-private-assets gate:

\`\`\`sh
scripts/xbox-browser-boot-verify-synthetic.sh
\`\`\`

After local fixtures exist, validate them first:

\`\`\`sh
scripts/xbox-real-fixtures-ready.sh
XEMU_REAL_B3_PREFLIGHT_ONLY=1 scripts/xbox-real-b3-matrix.sh
\`\`\`

Then run the real B3 matrix:

\`\`\`sh
scripts/xbox-real-b3-matrix.sh
\`\`\`

For full completion audit:

\`\`\`sh
scripts/xbox-boot-completion-audit.sh
\`\`\`

## Raw Evidence

\`\`\`text
$(cat "${tmp_summary}")
\`\`\`
EOF

printf 'BOOT_EVIDENCE_REPORT result=pass output=%s summary=%s next=%s\n' \
    "${output}" "${summary_result}" "${next_step}"
