#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: scripts/xbox-real-fixture-manifest.sh [out-dir]

Writes a no-emulation real-fixture handoff manifest. The manifest records
readiness and git privacy evidence for the local private Xbox fixtures without
copying files, hashing files, or reading contents beyond size checks performed
by scripts/xbox-real-fixtures-ready.sh.

Defaults:
  out-dir: build-real-fixture-manifest

Controls:
  XEMU_REAL_FIXTURE_MANIFEST_REQUIRE  Exit nonzero unless result=pass when set to 1.
  XEMU_REAL_B3_FIXTURE_DIR            Optional fixture dir for auto-discovery.
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
out_dir="${1:-${repo_root}/build-real-fixture-manifest}"
require_pass="${XEMU_REAL_FIXTURE_MANIFEST_REQUIRE:-0}"

case "${out_dir}" in
    /*) ;;
    *) out_dir="${repo_root}/${out_dir}" ;;
esac

mkdir -p "${out_dir}"
readiness_log="${out_dir}/real-fixture-ready.log"
privacy_log="${out_dir}/fixture-privacy.log"
manifest_md="${out_dir}/real-fixture-manifest.md"

latest_value_for() {
    local file="$1"
    local prefix="$2"
    local key="$3"
    local line
    local token

    line="$(grep "^${prefix} " "${file}" | tail -n 1 || true)"
    for token in ${line}; do
        case "${token}" in
            "${key}="*)
                printf '%s' "${token#*=}"
                return
                ;;
        esac
    done
}

latest_line() {
    local file="$1"
    local pattern="$2"

    grep -E "${pattern}" "${file}" | tail -n 1 || true
}

set +e
"${repo_root}/scripts/xbox-real-fixtures-ready.sh" >"${readiness_log}" 2>&1
readiness_status="$?"
"${repo_root}/scripts/xbox-fixture-privacy-check.sh" "${repo_root}" >"${privacy_log}" 2>&1
privacy_status="$?"
set -e

readiness_result="$(latest_value_for "${readiness_log}" REAL_FIXTURE_READY_RESULT result)"
readiness_next="$(latest_value_for "${readiness_log}" REAL_FIXTURE_READY_RESULT next)"
privacy_result="$(latest_value_for "${privacy_log}" FIXTURE_PRIVACY_RESULT result)"
flash_line="$(latest_line "${readiness_log}" '^REAL_FIXTURE_READY item=flash ')"
hdd_line="$(latest_line "${readiness_log}" '^REAL_FIXTURE_READY item=hdd ')"
mcpx_line="$(latest_line "${readiness_log}" '^REAL_FIXTURE_READY item=mcpx ')"
eeprom_line="$(latest_line "${readiness_log}" '^REAL_FIXTURE_READY item=eeprom ')"
dvd_line="$(latest_line "${readiness_log}" '^REAL_FIXTURE_READY item=dvd ')"

if [ -z "${readiness_result}" ]; then
    readiness_result="fail"
    readiness_next="inspect-readiness-log"
fi
if [ -z "${privacy_result}" ]; then
    privacy_result="fail"
fi

if [ "${privacy_status}" -ne 0 ] || [ "${privacy_result}" != "pass" ]; then
    result="fail"
    next="fix-fixture-privacy"
elif [ "${readiness_result}" = "pass" ]; then
    result="pass"
    next="real-b3-preflight"
elif [ "${readiness_result}" = "missing-required" ]; then
    result="missing-required"
    next="add-fixtures"
else
    result="fail"
    next="${readiness_next:-fix-fixtures}"
fi

cat >"${manifest_md}" <<EOF
# Real Xbox Fixture Manifest

Generated by \`scripts/xbox-real-fixture-manifest.sh\`.

This manifest is a no-emulation handoff artifact. It records paths, sizes, and
git privacy status only. It does not copy, hash, or inspect proprietary fixture
contents.

## Summary

| Field | Value |
| --- | --- |
| Result | ${result} |
| Readiness result | ${readiness_result} |
| Privacy result | ${privacy_result} |
| Next step | ${next} |

## Fixture Readiness

| Fixture | Latest evidence |
| --- | --- |
| Flash | ${flash_line:-not reported} |
| HDD | ${hdd_line:-not reported} |
| MCPX | ${mcpx_line:-not reported} |
| EEPROM | ${eeprom_line:-not reported} |
| DVD | ${dvd_line:-not reported} |

## Evidence Files

| File | Purpose |
| --- | --- |
| ${readiness_log} | Real fixture path and size readiness. |
| ${privacy_log} | Git ignore/tracking privacy check. |

## Next Command

\`\`\`sh
scripts/xbox-boot-next-step.sh
\`\`\`

EOF

cat "${readiness_log}"
cat "${privacy_log}"
printf 'REAL_FIXTURE_MANIFEST item=readiness status=%s exit=%s log=%s\n' \
    "${readiness_result}" "${readiness_status}" "${readiness_log}"
printf 'REAL_FIXTURE_MANIFEST item=privacy status=%s exit=%s log=%s\n' \
    "${privacy_result}" "${privacy_status}" "${privacy_log}"
printf 'REAL_FIXTURE_MANIFEST_RESULT result=%s next=%s output=%s readiness_log=%s privacy_log=%s require=%s\n' \
    "${result}" "${next}" "${manifest_md}" "${readiness_log}" "${privacy_log}" "${require_pass}"

if [ "${require_pass}" = "1" ] && [ "${result}" != "pass" ]; then
    exit 2
fi
